### ISSUE TITLE
Update list of properties that use URLs but not be referenced

### ISSUE THREAD

**Issue by paulrobertlloyd** [getindiekit/mf2tojf2#26]
Currently `mf2tojf2referenced` fetches information about every property value that is a URL, except if the property key is `url` (preventing it from fetching information about itself):

https://github.com/getindiekit/mf2tojf2/blob/18b76b22c22dd502a3482bcc2e10e0f2a61c595e/lib/fetch-references.js#L18

However, other properties can contain URLs, but don’t benefit from referencing. For example `mp-syndicate-to`, which is used as a directive for Micropub servers, same too for `mp-destination`.

Is there a list of property names, besides `url`, that should be excluded from triggering referencing? Perhaps we prevent referencing for any property that starts with `mp-`, as well as `url`?

@aciccarello: be keen to get your thoughts on this!

**Comment by aciccarello** [comment]
I don't see too much risk to over-fetching. Especially with potential new properties like `review-of` staying flexible with changed would probably be simplest. But I agree it would make sense to skip some known, self-references. I haven't dug into the `mp-` properties deeply but seeing as those are usually directives to do something it would make sense to skip them all.
